### ISSUE TITLE
AttributeError: 'XSOEnumMixin' object has no attribute 'name' (Python 3.11.3 bug)

### ISSUE THREAD

**Issue by C0D3D3V** [horazont/aioxmpp#391]
aioxmpp raise an exception on import in python 3.11 see:
https://github.com/C0D3D3V/Moodle-DL/issues/191

**Comment by Luc1412** [comment]
This change, which triggers this error, has been introduced in Python 3.11.3. Python 3.11.2 should work fine.

**Comment by pszafer** [comment]
Is there any plan to fix that? So it will work with all Python 3.11 versions?

**Comment by horazont** [comment]
I was hoping that 3.11.3 would land in my distro so I can test and fix this painlessly, but as it seems I'll have to docker my way around it, so it'll take some time (unless someone else comes up with a patch).

**Comment by slovdahl** [comment]
@horazont have you tried [pyenv](https://github.com/pyenv/pyenv)?

**Comment by horazont** [comment]
I looked at the issue, and it seems to be more tricky than it looks in the first place.

Even if the immediate issue (`name` not being available) is worked around, how enums work seems to have changed significantly and it then breaks a bunch of tests.

Will take some more time to look into this, unless someone else chimes in.

Here's the patch I used to get beyond the first error; aioxmpp then imports fine, but the test suite breaks:

```diff
diff --git a/aioxmpp/xso/model.py b/aioxmpp/xso/model.py
index 88b783a1..589b3fb5 100644
--- a/aioxmpp/xso/model.py
+++ b/aioxmpp/xso/model.py
@@ -2920,23 +2920,25 @@ class XSOEnumMixin:
 
     def __init__(self, namespace, localname):
         super().__init__()
-        self.xso_class = self._create_class()
+        self.xso_class = self._create_class((namespace, localname))
 
     def _create_name(self):
         return "".join(map(str.title, self.name.split("_")))
 
-    def _create_class(self):
+    def _create_class(self, tag):
         def to_xso(self):
             return self
 
         return XMLStreamClass(
-            self._create_name(),
+            #self._create_name(),
+            "",
             (XSO,),
             {
-                "TAG": self.value,
+                "TAG": tag,
                 "__qualname__": "{}.{}.xso_class".format(
                     type(self).__qualname__,
-                    self.name,
+                    #self.name,
+                    "_variant",
                 ),
                 "enum_member": self,
                 "to_xso": to_xso,
```

**Comment by slovdahl** [comment]
I'm guessing this broke because of https://github.com/python/cpython/issues/102549? I couldn't find anything else that seemed related in https://docs.python.org/release/3.11.3/whatsnew/changelog.html#python-3-11-3 at least.

I have no idea about anything in `aioxmpp` (or XMPP in general for that matter), so bear with me 😁

I suppose the `self.name` and `self.value` references here are meant to refer to the name and value of the enum this mixin is used in? How could it ever have worked in the first place? I mean, how could `self.xso_class` have ever been set to something?

I tried cloning the repo and running the test suite locally but for some reason I'm just getting `ModuleNotFoundError: No module named 'babel'` failures despite having all the required dependencies installed 🤔

**Comment by slovdahl** [comment]
Ah, right, assuming the `XSOEnumMixin` is used like 👇 it seems like it has worked. But obviously not without the `XSOEnumMixin.__init__` call.

```python
class Foo(XSOEnumMixin, enum.Enum):
    # ...

    def __init__(self, ..):
        XSOEnumMixin.__init__(self)
        # ...
```

**Comment by slovdahl** [comment]
I wonder if this is a regression in Python that has already been fixed. 🤔 https://github.com/python/cpython/issues/102549 was fixed in 3.11.3, but shortly after 3.11.3 was released, https://github.com/python/cpython/issues/103479 was reported and subsequently fixed in https://github.com/python/cpython/pull/103495 (and backported in https://github.com/python/cpython/pull/103514).

I have not actually tested this with `aioxmpp`, but I tried to extract the least amount of code that could reproduce the same issue. 

```python
import enum

class EnumMixin:
    def __init__(self):
        self._tag = self._create_name()

    def _create_name(self):
        return f'{self.name}'

    def tag(self):
        return self._tag

class TestEnum(EnumMixin, enum.Enum):
    A = 'a'

    def __init__(self, y):
        EnumMixin.__init__(self)
        self.y = y

print(f'{TestEnum.A.tag()}')
```

With Python 3.11.2 the code above works fine:

```shell
$ ~/.pyenv/versions/3.11.2/bin/python test.py 
A
```

Python 3.11.3 gives this error:

```shell
$ ~/.pyenv/versions/3.11.3/bin/python test.py 
Traceback (most recent call last):
  File "/Users/slovdahl/.pyenv/versions/3.11.3/lib/python3.11/enum.py", line 260, in __set_name__
    enum_member._value_ = enum_class._member_type_(*args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EnumMixin.__init__() takes 1 positional argument but 2 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/slovdahl/dev/external/aioxmpp/test.py", line 13, in <module>
    class TestEnum(EnumMixin, enum.Enum):
  File "/Users/slovdahl/.pyenv/versions/3.11.3/lib/python3.11/enum.py", line 557, in __new__
    raise exc
  File "/Users/slovdahl/.pyenv/versions/3.11.3/lib/python3.11/enum.py", line 266, in __set_name__
    raise new_exc
TypeError: _value_ not set in __new__, unable to create it
```

After manually applying https://github.com/python/cpython/commit/3b929a7b321dae113593d81caf47c4f08890c615#diff-e5dd6e444e4e6c2cdeb8edf271d057f9da52f7b406dcd8b655dc396fb013bd03R990 for my Python 3.11.3 installation:

```shell
$ ~/.pyenv/versions/3.11.3/bin/python test.py 
A
```

What do you think @horazont, does this make sense?

**Comment by slovdahl** [comment]
According to https://peps.python.org/pep-0664/#bugfix-releases, 3.11.4 will be released on Monday 2023-06-05. 🤞

**Comment by horazont** [comment]
:eyes:

Thanks for tracking this down, @slovdahl! I'll give it a shot with 3.11.4 in docker next week then to see if that fixes it!

**Comment by slovdahl** [comment]
3.11.4 has been released now 🙂

**Comment by horazont** [comment]
As far as I can tell, 3.11.4 works :-)

So I'm gonna close this because it's not an aioxmpp bug (yay!)
