### ISSUE TITLE
Support for XMPP over TLS and XEP-0368

### ISSUE THREAD

**Issue by azmeuk** [horazont/aioxmpp#16]
Hi.
Searching in the code and the documentation, it seems that the only transport layer security provider is [STARTTLSProvider](https://docs.zombofant.net/aioxmpp/0.5/api/public/security_layer.html?highlight=starttlsprovider#transport-layer-security-provider). Yet some services, like [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/server#connecting) does not support STARTTLS (yet?).

Is there currently a way to avoid STARTTLS, or is there another non STARTTLS security provider planed?

Thanks.

**Comment by horazont** [comment]
I do not plan to implement a way to connect without STARTTLS myself.

If someone creates a pull request, I would merge it though. The most sensible way would be for aioxmpp.security_layer.negotiate_stream_security to allow skipping the TLS negotiation step. Ensure proper testing though.

**Comment by horazont** [comment]
Although: If Firebase Cloud Messaging does not incorrectly advertise STARTTLS and you set require_starttls to False in the STARTTLSProvider, you should be fine. It will not attempt to negotiate STARTTLS in that case if the peer does not advertise support for it.

**Comment by horazont** [comment]
I just now realized that Firebase Cloud Messaging requires plain, non-STARTTLS TLS, which I did not get from your initial post.

This is a larger problem, and this indeed needs to be fixed. The following steps are required:

* [ ] The ``override_peer`` argument should probably get another element which specifies whether direct TLS shall be used.
* [ ] The ``STARTTLSProvider`` needs to be able to detect that direct TLS has been used and skip the STARTTLS step in that case—even if TLS is set to required (currently, it would fail there).
* [ ] Implement [XEP-0368 "SRV records for XMPP over TLS"](https://xmpp.org/extensions/xep-0368.html)

**Comment by horazont** [comment]
@azmeuk I just pushed a bunch of commits which should fix your problem.

Use aioxmpp from devel if you can, and then pass

```python
    override_peer=[("fcm-xmpp.googleapis.com", 
                    5235, 
                    aioxmpp.connector.XMPPOverTLSConnector())],
```

to your AbstractClient / PresenceManagedClient.

This will force aioxmpp to use XMPP-over-TLS and the given host+port. It will do that before it tries the SRV records, so if that connection succeeds, you are good to go.

Please let me know if it works for you or if you need anything else. I’m planning to push out a release (0.6) this weekend, including this feature.

**Comment by azmeuk** [comment]
Thank you very much for your quick fix! It seem to connect and behave as expected.

Though I spent the afternoon trying to build a simple 'send and quit' script, but I cannot make it work properly. Maybe you can help? I am sure I missed something obvious here.

The following code prints me an empty message `<message id=''>{}</message>` where I expect something like described [in the documentation](https://firebase.google.com/docs/cloud-messaging/server#format): `<message id=""><gcm xmlns="google:mobile:data">{...JSON payload....}</gcm></message>`.

```python
import asyncio, datetime, uuid, logging, json, aioxmpp.xso, aioxmpp.utils, aioxmpp.node, aioxmpp.security_layer, aioxmpp.stanza, aioxmpp.structs
from . import settings

class FCMPayload(aioxmpp.xso.XSO):
    TAG = (aioxmpp.utils.namespaces.client, "gcm")
    xmlns = aioxmpp.xso.Attr(tag="xmlns", default="google:mobile:data")
    text = aioxmpp.xso.Text(default=None)

    def __repr__(self):
        return '<gcm xmlns={!r}>{!s}</gcm>'.format(self.xmlns, self.text)

class FCMMessage(aioxmpp.stanza.StanzaBase):
    TAG = (aioxmpp.utils.namespaces.client, "message")
    id_ = aioxmpp.xso.Attr(tag="id", default="")
    payload = aioxmpp.xso.ChildTextMap(FCMPayload)

    def __repr__(self):
        return '<message id={!r}>{!r}</message>'.format(self.id_, self.payload)

async def main(jid, password, recipient):
    @asyncio.coroutine
    def get_password(client_jid, nattempt):
        return None if nattempt > 1 else password

    client = aioxmpp.node.PresenceManagedClient(
        jid,
        aioxmpp.security_layer.tls_with_password_based_authentication(get_password),
        override_peer = [(settings.FCM_SERVER_URL, settings.FCM_SERVER_PORT, aioxmpp.connector.XMPPOverTLSConnector())],
    ) 

    async with aioxmpp.node.UseConnected(client, timeout=datetime.timedelta(seconds=30)) as stream:
        payload = json.dumps({
            "message_id": str(uuid.uuid4()),
            "to": settings.RECIPIENT,
            "notification": { 
                "title": "Hello",
                "text": "World",
            } 
        })

        msg = FCMMessage()
        msg.payload.text = payload
        print(msg)
        await stream.send_and_wait_for_sent(msg)

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG, format='%(levelname)-7s %(module)s:%(lineno)-4s %(message)s')
    jid = aioxmpp.structs.JID.fromstr(settings.FCM_JID)
    recipient = aioxmpp.structs.JID.fromstr(settings.RECIPIENT)
    asyncio.get_event_loop().run_until_complete(main(jid, settings.FCM_API_KEY, recipient))
```

**Comment by horazont** [comment]
First of all, I suggest you use aioxmpp.stanza.Message and add a descriptor to it for your application instead of defining your own stanza. Using your own stanza will have effects you do not want or anticipate (such as, received stanzas will still have aioxmpp.stanza.Message type and your payload will be discarded as unknown).

To do so, use the following code:
```python
aioxmpp.stanza.fcm_payload = aioxmpp.xso.Child([FCMPayload])
```
Note that I’m using ``Child([FCMPayload])`` here, for testing.

Second, do not define ``xmlns`` attributes. This is asking for trouble, and I should probably add code which prohibits that. The XML namespace will be automatically declared by the XML serialiser as needed (but see also [the documentation of the DECLARE_NS class attribute](https://docs.zombofant.net/aioxmpp/devel/api/public/xso.html#aioxmpp.xso.model.XMLStreamClass.DECLARE_NS) if you need more control; by default, the attribute is set so that the namespace of the ``TAG`` is declared as prefixless namespace on the element). To define in which namespace your element is, use the ``TAG`` class attribute:

```python
class FCMPayload(aioxmpp.xso.XSO):
    TAG = ("google:mobile:data", "gcm")
    text = aioxmpp.xso.Text(default=None)
```

Now compose your message like this:

```python
payload = FCMPayload()
payload.text = json.dumps({
            "message_id": str(uuid.uuid4()),
            "to": recipient,
            "notification": { 
                "title": "Hello",
                "text": "World",
            } 
})
msg = aioxmpp.stanza.Message(type_="normal")
msg.fcm_payload = payload
```

Improvement 1: Custom ``JSON`` type
---

If that works, it might make sense to create a JSON-type which can be used with aioxmpp.xso.Text. Have a look at the aioxmpp.xso.types module to see how it works in principle. I would appreciate a pull request if you’d like to add such a type to aioxmpp. With such a type, we could simplify the code to:

```python
class FCMPayload(aioxmpp.xso.XSO):
    TAG = ("google:mobile:data", "gcm")
    json = aioxmpp.xso.Text(default=None, type_=aioxmpp.xso.JSON)
```

```python
payload = FCMPayload()
payload.json = {
            "message_id": str(uuid.uuid4()),
            "to": recipient,
            "notification": { 
                "title": "Hello",
                "text": "World",
            } 
}
msg = aioxmpp.stanza.Message(type_="normal")
msg.fcm_payload = payload
```

Improvement 2: use ``ChildText`` to save the FCMPayload class
---

In addition, you can now also use (provided there is at most one ``<gcm/>`` in each message, both when received and sent):

```python
aioxmpp.stanza.Message.fcm_payload = aioxmpp.xso.ChildText(
   ("google:mobile:data", "gcm"),
   type_=aioxmpp.xso.JSON(),
   default=None,
)
```

This saves the ``FCMPayload`` class and allows to compose the message like this:

```python
msg = aioxmpp.stanza.Message(type_="normal")
msg.fcm_payload = {
            "message_id": str(uuid.uuid4()),
            "to": recipient,
            "notification": { 
                "title": "Hello",
                "text": "World",
            } 
}
```

(Of course, even without the JSON type, you can use json.dumps with the above).

Let me know how this works out for you!

**Comment by azmeuk** [comment]
Thank you! This is working pretty well. I will try to make you some pull requests asap.
One last question. How can I exit the program properly, and avoid EOF exceptions? The following code produces [this output](https://gist.github.com/azmeuk/227b8e8f6adf92e08a6ffc2425310d0a).

```python
import asyncio, datetime, uuid, logging, json, aioxmpp.xso, aioxmpp.utils, aioxmpp.node, aioxmpp.security_layer, aioxmpp.structs, aioxmpp.stanza, settings

class FCMPayload(aioxmpp.xso.XSO):
    TAG = ("google:mobile:data", "gcm")
    text = aioxmpp.xso.Text(default=None)

async def main(jid, password, recipient):
    @asyncio.coroutine
    def get_password(client_jid, nattempt):
        return None if nattempt > 1 else password

    aioxmpp.stanza.Message.fcm_payload = aioxmpp.xso.Child([FCMPayload])

    client = aioxmpp.node.PresenceManagedClient(
        jid,
        aioxmpp.security_layer.tls_with_password_based_authentication(get_password),
        override_peer = [(settings.FCM_SERVER_URL, settings.FCM_SERVER_PORT, aioxmpp.connector.XMPPOverTLSConnector())],
    ) 

    async with aioxmpp.node.UseConnected(client, timeout=datetime.timedelta(seconds=30)) as stream:
        payload = FCMPayload()
        payload.text = json.dumps({
            "message_id": str(uuid.uuid4()),
            "to": recipient,
            "notification": { 
                "title": "Hello", "text": "World",
            } 
        })

        msg = aioxmpp.stanza.Message(type_="normal")
        msg.fcm_payload = payload
        await stream.send_and_wait_for_sent(msg)

if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG, format='%(levelname)-7s %(module)s:%(lineno)-4s %(message)s')
    jid = aioxmpp.structs.JID.fromstr(settings.FCM_JID)

    asyncio.get_event_loop().run_until_complete(main(jid, settings.FCM_API_KEY, settings.RECIPIENT))
```

**Comment by horazont** [comment]
There are two reasons how this can happen:

1. aioxmpp has waited for 15 seconds for the stream footer and did not receive it. You can confirm that by adding timestamps to the log or simply checking whether it is actually waiting for 15 seconds before the EOF happens. Then it will brutally close the TCP connection on the client side which may easily confuse the SSL stack; even though I have not yet observed that.

2. The server simply shuts down the TCP stream without sending the stream footer or closing the TLS connection properly first. In that case there’s not much you can do about it.

If it is option 1, there may be something we could do about it, but I don’t regard it as *too* critical at the moment, if everything else gets cleaned up properly and does not hang. If it is option 2, there’s not much we can do except complaining at the server implementation.

**Comment by azmeuk** [comment]
The whole script is executed in a few seconds, so it must be option 2.

**Comment by horazont** [comment]
So I assume we can close this :-)

**Comment by azmeuk** [comment]
Looking again at the gist, I see a STARTTLS error:
```ERROR base_events:1090 Fatal read error on STARTTLS transport```
But wasn't the `override_peer` option supposed to avoid to use STARTTLS?

**Comment by horazont** [comment]
Ah, don’t be confused. This is a legacy misnomer of the STARTTLSTransport class, which is really mostly a re-implementation of the SSL Transport offered by asyncio, but using PyOpenSSL instead of the built-in ssl module and *in addition* supporting STARTTLS. It can also be used as (and is used by the TLSOverXMPPConnector) normal SSL transport.

**Comment by azmeuk** [comment]
> 2. The server simply shuts down the TCP stream without sending the stream footer or closing the TLS connection properly first. In that case there’s not much you can do about it.

> If it is option 1, there may be something we could do about it, but I don’t regard it as too critical at the moment, if everything else gets cleaned up properly and does not hang. If it is option 2, there’s not much we can do except complaining at the server implementation.

So it seems Google just closes the connection without properly closing the TLS connection. Is there a way to catch the exception? Since it is an expected behavior, I would like to silence it.

**Comment by azmeuk** [comment]
Sorry to bother you again with this old issue. I am meeting some new problems. I think this is because the library has changed since last summer. I work with the 0.7.0 version, and I encounter this traceback with a very similar code:
```python
Traceback (most recent call last):
  File "/home/eloi/dev/push-server/local.virtualenv/lib/python3.5/site-packages/aioxmpp/stream.py", line 680, in _done_handler
    task.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/eloi/dev/push-server/local.virtualenv/lib/python3.5/site-packages/aioxmpp/stream.py", line 1661, in _run
    incoming_fut.result())
  File "/home/eloi/dev/push-server/local.virtualenv/lib/python3.5/site-packages/aioxmpp/stream.py", line 957, in _process_incoming
    self._process_incoming_message(stanza_obj)
  File "/home/eloi/dev/push-server/local.virtualenv/lib/python3.5/site-packages/aioxmpp/stream.py", line 811, in _process_incoming_message
    (stanza_obj.type_, stanza_obj.from_.bare()),
AttributeError: 'NoneType' object has no attribute 'bare'
```
Here is [the code I used and the full traceback](https://gist.github.com/azmeuk/ea229445019d2fa7c16d809369b1b38a).

**Comment by horazont** [comment]
No matter what, the last one is a bug. The other one should also be fixed to reduce confusion, you’re right about that one.

Please open a new issue for each of them, so I can track them separately.

Also hang on, I’m currently sick and probably won’t get around to look at it this week.

**Comment by azmeuk** [comment]
No problem, take your time to heal!
Thank you for being reactive.
